//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantisBase2ApiRestSharpNetCore.Queries {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectQueries() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MantisBase2ApiRestSharpNetCore.Queries.ProjectQueries", typeof(ProjectQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM mantis_project_table.
        /// </summary>
        internal static string DeleteProjectMassa {
            get {
                return ResourceManager.GetString("DeleteProjectMassa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO mantis_project_table ( name, status, enabled, view_state, access_min, file_path, description, category_id, inherit_global)
        ///                                 VALUES(&apos;$project1&apos;, 10,1, 10, 10, &apos;file&apos;, &apos;description&apos;, 1, 1).
        /// </summary>
        internal static string InsertProjectOne {
            get {
                return ResourceManager.GetString("InsertProjectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO mantis_project_table ( name, status, enabled, view_state, access_min, file_path, description, category_id, inherit_global)
        ///                                 VALUES(&apos;$project3&apos;, 10,1, 10, 10, &apos;file&apos;, &apos;description&apos;, 1, 1).
        /// </summary>
        internal static string InsertProjectThree {
            get {
                return ResourceManager.GetString("InsertProjectThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO mantis_project_table ( name, status, enabled, view_state, access_min, file_path, description, category_id, inherit_global)
        ///                                 VALUES(&apos;$project2&apos;, 10,1, 10, 10, &apos;file&apos;, &apos;description&apos;, 1, 1).
        /// </summary>
        internal static string InsertProjectTwo {
            get {
                return ResourceManager.GetString("InsertProjectTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT id, name FROM mantis_custom_field_table.
        /// </summary>
        internal static string ReturnField {
            get {
                return ResourceManager.GetString("ReturnField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT id, NAME, status FROM mantis_project_table order by 1 desc LIMIT 1.
        /// </summary>
        internal static string ReturnProject {
            get {
                return ResourceManager.GetString("ReturnProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT id, name, enabled FROM mantis_project_table where name=&apos;$nameProject&apos;.
        /// </summary>
        internal static string ReturnProjectCreate {
            get {
                return ResourceManager.GetString("ReturnProjectCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT count(*) FROM mantis_project_table where id=&apos;$id&apos;.
        /// </summary>
        internal static string ReturnProjectDelete {
            get {
                return ResourceManager.GetString("ReturnProjectDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT count(*) FROM mantis_project_table where name=&apos;$nameProject&apos;.
        /// </summary>
        internal static string ReturnProjectExists {
            get {
                return ResourceManager.GetString("ReturnProjectExists", resourceCulture);
            }
        }
    }
}
