//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantisBase2ApiRestSharpNetCore.Queries {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserQueries() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MantisBase2ApiRestSharpNetCore.Queries.UserQueries", typeof(UserQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete from mantis_user_table where username = &apos;$username&apos;.
        /// </summary>
        internal static string DeleteUserCreate {
            get {
                return ResourceManager.GetString("DeleteUserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO mantis_user_table ( username, realname, email,
        ///                PASSWORD, enabled, protected, access_level, login_count, lost_password_request_count, failed_login_count, cookie_string, last_visit, date_created)
        ///                VALUES(&apos;NameUserAPI1&apos;, &apos;NameUserAPI1Real&apos;,&apos;NameUserAPI1@gmail.com&apos;, &apos;c47ab4d1fa888162970af89ecc20b814&apos;, 1, 0, 40, 1, 0, 0, &apos;1dQWABu0o7OeIevEVc8LYutOlaENPXpHpPl_F3B__Hk3wSOWpepCblOqKiwuZkO_&apos;, 1645659881, 1645659881).
        /// </summary>
        internal static string InsertUserOne {
            get {
                return ResourceManager.GetString("InsertUserOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO mantis_user_table ( username, realname, email,
        ///                PASSWORD, enabled, protected, access_level, login_count, lost_password_request_count, failed_login_count, cookie_string, last_visit, date_created)
        ///                VALUES(&apos;NameUserAPI3&apos;, &apos;NameUserAPI3Real&apos;,&apos;NameUserAPI3@gmail.com&apos;, &apos;a27c5d499c7ed174319d7a88e168ad48&apos;, 1, 0, 40, 1, 0, 0, &apos;3TeUjXU7FcgUHLwulJmPnPh_WRYP7IMg_M_PTB2VQrps2AekDha06WVt5R6_plg7&apos;, 1645659881, 1645659881).
        /// </summary>
        internal static string InsertUserThree {
            get {
                return ResourceManager.GetString("InsertUserThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO mantis_user_table ( username, realname, email,
        ///                PASSWORD, enabled, protected, access_level, login_count, lost_password_request_count, failed_login_count, cookie_string, last_visit, date_created)
        ///                VALUES(&apos;NameUserAPI2&apos;, &apos;NameUserAPI2Real&apos;,&apos;NameUserAPI2@gmail.com&apos;, &apos;7b34326b9dfc1c88237a39a46d4e9017&apos;, 1, 0, 40, 1, 0, 0, &apos;21KhzlVkCPVz9mkx-C7TuQbqtKjsRhY8p3Mhup25alKyOt8vQeO1MM9cF2am_4df&apos;, 1645659881, 1645659881).
        /// </summary>
        internal static string InsertUserTwo {
            get {
                return ResourceManager.GetString("InsertUserTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT count(*) FROM mantis_user_table where id=&apos;$idUser&apos;.
        /// </summary>
        internal static string ReturnCountUserDelete {
            get {
                return ResourceManager.GetString("ReturnCountUserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT id FROM mantis_user_table WHERE (username NOT IN (&apos;administrador&apos;) AND access_level NOT IN (90)) and protected=0 LIMIT 1.
        /// </summary>
        internal static string ReturnIdUserDelete {
            get {
                return ResourceManager.GetString("ReturnIdUserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT id FROM mantis_user_table WHERE (username NOT IN (&apos;administrador&apos;) AND access_level NOT IN (90)) and protected=1 LIMIT 1.
        /// </summary>
        internal static string ReturnIdUserDeleteProtected {
            get {
                return ResourceManager.GetString("ReturnIdUserDeleteProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT username, email FROM mantis_user_table LIMIT 1.
        /// </summary>
        internal static string ReturnNameEmail {
            get {
                return ResourceManager.GetString("ReturnNameEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT count(*) FROM mantis_user_table where username = &apos;$username&apos;.
        /// </summary>
        internal static string ReturnUser {
            get {
                return ResourceManager.GetString("ReturnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT id, username, realname, email, access_level, enabled, protected  FROM mantis_user_table where access_level=90 and username = &apos;administrator&apos;.
        /// </summary>
        internal static string ReturnUserAdministrator {
            get {
                return ResourceManager.GetString("ReturnUserAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT id, username, realname, email, access_level, enabled, protected  FROM mantis_user_table where id=&apos;$id&apos; .
        /// </summary>
        internal static string ReturnUserCreate {
            get {
                return ResourceManager.GetString("ReturnUserCreate", resourceCulture);
            }
        }
    }
}
